### ISSUE TITLE
SwiftUI with openURL Example

### ISSUE THREAD

**Issue by ksteigerwald** [TizianoCoroneo/Deeplink#2]
I just wanted to reach out and say that I think your Deeplink library is excellent, and I'm really impressed with the addition of DocC tutorials. Your work is making it so much easier for developers to implement deep linking in their projects.

I'm actually using Deeplink in a SwiftUI project, and I was wondering if you might be able to provide an example of how you envision working with Deeplink and onOpenURL in a SwiftUI project. I think it would be really helpful to have an example to work off of.

Thanks again for your great work on this library, and I look forward to hearing back from you.

**Comment by TizianoCoroneo** [comment]
Thank you so much for the kind words 🥹

The app I'm working for is not yet at the stage where we can use SwiftUI `onOpenURL` (due to an ominous mountain of legacy UIKit stuff), so this has not been a priority for us; that said, I have several projects in my ~~graveyard~~ back burner that would benefit from a clearer integration. 

I'd love to give a look at how to do that, but I fear you'll have to wait a bit, at least until this weekend.
For context, I've gone back to university to get the degree I've never completed, so I'm double busy 😅

There are some other enhancements that I would like to make:
- a simple way to add unit tests (and relative docs)
- publishing docs in GitHub pages (wasn't possible when I made the docs, but it is now)
- fixing GitHub actions tests
- adding sample project/playground

Thanks again for reaching out!

**Comment by TizianoCoroneo** [comment]
@ksteigerwald, I gave a look at your use case of `onOpenURL` in a SwiftUI project. 
I came up with a working but somewhat unsatisfying solution, so I don't think I'm going to commit it to the repo as an official sample project. However, here's the code if you'd like to give a look. 
The main idea is to wrap the `DeeplinkCenter` inside an `ObservableObject`, setting an internal `Published` properties that contains enough data to identify which link was triggered and with what data, and using that to modify the content of a view. From there you could use `onChange` in the inner views to trigger other side effects.

Let me know what you think! I also realized that we probably need a simple curve of adoption for SwiftUI project, and different samples for different use cases (what if you want to set a `NavigationPath`, using the new SwiftUI `NavigationStack`? What if you want to use something like The Composable Architecture?)

[Deeplink with sample project.zip](https://github.com/TizianoCoroneo/Deeplink/files/10888638/Deeplink.with.sample.project.zip)

**Comment by ksteigerwald** [comment]
Thanks! I ended up using the onOpneURL, but I like your handler, so I will make use of this for sure.
